# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BIFf-XI3c5OQzn_rFhSlqScmOXtpbGqu
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import torchvision.utils as vutils
import matplotlib.pyplot as plt
import os

!pip install datasets
from datasets import load_dataset
from PIL import Image

os.makedirs("/content/data/faces", exist_ok=True)

ds = load_dataset("merkol/ffhq-256", split="train")

for i, item in enumerate(ds):
    item["image"].save(f"/content/data/faces/{i:05d}.jpg")
    if i % 1000 == 0:
        print(f"{i}/{len(ds)} saved...")

img = Image.open("/content/data/faces/00000.jpg")
plt.imshow(img)
plt.axis("off")
plt.show()

DATAROOT   = "/content/data"   # Folder containing the dataset (ImageFolder expects subfolders inside)
BATCH_SIZE = 128               # How many images to process per training step
IMAGE_SIZE = 64                # Resize all images to 64×64 — DCGAN was designed around this size
NC         = 3                 # Number of image channels — 3 for RGB
NZ         = 100               # Length of the latent noise vector fed into the Generator
NGF        = 64                # Controls the width (number of feature maps) inside the Generator
NDF        = 64                # Controls the width (number of feature maps) inside the Discriminator
NUM_EPOCHS = 5                 # How many full passes through the dataset
LR         = 0.0002            # Learning rate — from the original DCGAN paper, works well as-is
BETA1      = 0.5               # Adam's momentum term — lower than default (0.9) for more stable GAN training
WORKERS    = 2

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using: {device}")

transform=transforms.Compose([
    transforms.Resize(IMAGE_SIZE),
    transforms.CenterCrop(IMAGE_SIZE),
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
])

dataset=torchvision.datasets.ImageFolder(
    root=DATAROOT,
    transform=transform,
)

dataloader=torch.utils.data.DataLoader(
    dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=WORKERS,
)

print(f"len of dataset {len(dataset):,} images, batches per epoch: {len(dataloader)}")

#weight initialisation
#dcgans paper says wwights from 0-0.2 is better than pytorchs default
def weights_init(m):
  classname=m.__class__.__name__ #get the layer type as a string
  if classname.find("Conv") !=-1:
    nn.init.normal_(m.weight.data,0.0,0.02)
  elif classname.find("BatchNorm") !=-1:
    nn.init.normal_(m.weight.data,1.0,0.02)
    nn.init.constant_(m.bias.data,0)

#GENERATOR
class Generator(nn.Module):
  def __init__(self):
    super().__init__()
    self.main=nn.Sequential(
        nn.ConvTranspose2d(NZ,NGF*8,4,1,0,bias=False),
        nn.BatchNorm2d(NGF*8),
        nn.ReLU(True),
        #block2
        nn.ConvTranspose2d(NGF*8,NGF*4,4,2,1,bias=False),
        nn.BatchNorm2d(NGF*4),
        nn.ReLU(True),
        #block3
        nn.ConvTranspose2d(NGF*4,NGF*2,4,2,1,bias=False),
        nn.BatchNorm2d(NGF*2),
        nn.ReLU(True),
        #block4
        nn.ConvTranspose2d(NGF * 2, NGF, 4, 2, 1, bias=False),
        nn.BatchNorm2d(NGF),
        nn.ReLU(True),
        #output block
        nn.ConvTranspose2d(NGF,NC,4,2,1,bias=False),
        nn.Tanh()
    )
  def forward(self,z):
    #inputshape: (batch_size,NZ,1,1)
    #output shape: (batch_size,NC,64,64)
    return self.main(z)

class Discriminator(nn.Module):
  def __init__(self):
    super().__init__()
    self.main=nn.Sequential(
        #block1 (NC,64,64) => (NDF,32,32)
        #no batchnorm
        nn.Conv2d(NC,NDF,4,2,1,bias=False),
        nn.LeakyReLU(0.2,inplace=True),
        #block2 (NDF,32,32)->(NDF*2,16,16)
        nn.Conv2d(NDF,NDF*2,4,2,1,bias=False),
        nn.BatchNorm2d(NDF*2),
        nn.LeakyReLU(0.2,inplace=True),
        #block3
        nn.Conv2d(NDF*2,NDF*4,4,2,1,bias=False),
        nn.BatchNorm2d(NDF*4),
        nn.LeakyReLU(0.2,inplace=True),
        #block4
        nn.Conv2d(NDF * 4, NDF * 8, 4, 2, 1, bias=False),
        nn.BatchNorm2d(NDF * 8),
        nn.LeakyReLU(0.2, inplace=True),
        #output
        nn.Conv2d(NDF*8,1,4,1,0,bias=False),
        nn.Sigmoid()


    )
  def forward(self,x):
    return self.main(x).view(-1)

#BUILD MODEL
netG=Generator().to(device)
netD=Discriminator().to(device)
netG.apply(weights_init)
netD.apply(weights_init)
print("models ready")

from torch.optim import optimizer
#Loss and optim
criterion=nn.BCELoss()

optimizerD=optim.Adam(netD.parameters(),lr=LR,betas=(BETA1,0.999))
optimizerG=optim.Adam(netG.parameters(),lr=LR,betas=(BETA1,0.999))

#noise
fixed_noise=torch.randn(64,NZ,1,1,device=device)
G_losses=[]
D_losses=[]
img_list=[]

#training loop
print("starting training loop")
for epoch in range(NUM_EPOCHS):
  for i,(real_images,_) in enumerate(dataloader):
    #train disc
    netD.zero_grad() #reset gradient from previous iteration
    real_images=real_images.to(device)
    b_size = real_images.size(0)
    batch_size=real_images.size(0)
    labels=torch.full((b_size,),1.0,device=device)

    output=netD(real_images)
    errD_real=criterion(output,labels)
    errD_real.backward()
    noise=torch.randn(b_size,NZ,1,1,device=device) #sample noise latent vector
    fake=netG(noise)
    labels.fill_(0.0) #label the fake data
    # .detach() cuts the fake tensor from G's computation graph
    # Without it, .backward() would try to compute gradients all the way back through G

    output=netD(fake.detach())
    errD_fake=criterion(output,labels)
    errD_fake.backward()
    optimizerD.step()

    errD=errD_real+errD_fake

    #Train generator

    netG.zero_grad()

    labels.fill_(1.0)
    output=netD(fake)
    errG=criterion(output,labels)
    errG.backward()
    optimizerG.step()

    #logging
    G_losses.append(errG.item())
    D_losses.append(errD.item())

    if i % 50 == 0:
            print(
                f"[{epoch+1}/{NUM_EPOCHS}][{i}/{len(dataloader)}] "
                f"Loss_D: {errD.item():.4f}  Loss_G: {errG.item():.4f}"
            )

 
    with torch.no_grad():
        fake_snapshot = netG(fixed_noise).detach().cpu()   
    # make_grid arranges 64 images into an 8×8 grid tensor
    # normalize=True rescales pixel values from [-1,1] back to [0,1] for display
    img_list.append(vutils.make_grid(fake_snapshot, normalize=True))

print("\nTraining done!")


torch.save(netD.state_dict(), "/content/discriminator.pth")



plt.figure(figsize=(10, 5))
plt.title("Generator and Discriminator Loss")
plt.plot(G_losses, label="Generator")
plt.plot(D_losses, label="Discriminator")
plt.xlabel("Iterations")
plt.ylabel("Loss")
plt.legend()
plt.show()



# img_list[-1] is the grid from the final epoch
# .permute(1, 2, 0) reorders dimensions from PyTorch's (C, H, W) to matplotlib's (H, W, C)
plt.figure(figsize=(8, 8))
plt.axis("off")
plt.title("Generated Faces — Final Epoch")
plt.imshow(img_list[-1].permute(1, 2, 0))
plt.show()


from google.colab import files
files.download("/content/generator.pth")
files.download("/content/discriminator.pth")




